### ISSUE TITLE
WRN-34-10 parameter settings

### ISSUE THREAD

**Issue by YNU-JI** [qizhangli/ST-AT#1]
Hello, I am very interested in your research. When I reproduced your code, I applied the hyperparameter settings on resnet-18 to WRN-34-10, but found that the results obtained were quite different from those in your paper. Could you please tell me about the hyperparameter settings on WRN-34-10 or point out which parts need to be adjusted?

**Comment by iamsh4shank** [comment]
Hi @YNU-JI were you able to find out what set of hyperparameters work for WRN-34-10? Thank you :D
